#!/bin/bash

set -e

export DOCKER_CLI_EXPERIMENTAL=enabled

DOCKER_BUILD_OPTS=''
if [ `docker version -f '{{.Server.Experimental}}'` = 'true' ]; then
  DOCKER_BUILD_OPTS="$DOCKER_BUILD_OPTS --squash"
fi

if [ ! -z "$DOCKERFILE_PATH" ]; then
  DOCKER_BUILD_OPTS="$DOCKER_BUILD_OPTS --file $DOCKERFILE_PATH"
fi

echo '==> preparing for build'
docker build -t $DOCKER_REPO:build-temp --target=build --build-arg VERSION=$VERSION --build-arg OS=linux --build-arg ARCH=amd64 $DOCKER_BUILD_OPTS .

# copy `.env` out and apply it
ctid=$(docker create $DOCKER_REPO:build-temp)
docker cp $ctid:/build/.env $PWD/.env.local
docker rm -fv $ctid

ORIGINAL_VERSION=$VERSION
. $PWD/.env.local

DOCKER_BUILD_OPTS="$DOCKER_BUILD_OPTS --build-arg BUILD_DATE=$BUILD_DATE"
DOCKER_BUILD_OPTS="$DOCKER_BUILD_OPTS --build-arg VCS_REF=$VCS_REF"
DOCKER_BUILD_OPTS="$DOCKER_BUILD_OPTS --build-arg VERSION=${ORIGINAL_VERSION:+$VERSION}"

echo
echo '==> building'
ARCH_ALL='386 amd64 arm arm64 mips mipsle mips64 mips64le'
for arch in $ARCH_ALL; do
  echo "  -> building for $arch..."

  EXTRA_OPTS="--build-arg OS=linux --build-arg ARCH=$arch"
  if [ "$arch" = "mips" ] || [ "$arch" = "mipsle" ]; then
    EXTRA_OPTS="$EXTRA_OPTS --build-arg GOMIPS=softfloat"
  fi

  docker build -t $DOCKER_REPO:$arch-v$VERSION $DOCKER_BUILD_OPTS $EXTRA_OPTS .
  echo
done

# cleanup
docker rmi $DOCKER_REPO:build-temp > /dev/null
