#!/bin/sh

set -e

BUILD_DIR=frp-builds

docker build --pull -t frpc-temp ./base
ctid=$(docker create frpc-temp)
docker cp $ctid:/frp-dist $(pwd)/$BUILD_DIR
docker rm -fv $ctid
docker rmi frpc-temp > /dev/null

export BUILD_DATE=`cat $BUILD_DIR/.BUILD_DATE`
export VERSION=`cat $BUILD_DIR/.VERSION`
export VCS_REF=`cat $BUILD_DIR/.VCS_REF`

export DOCKER_BUILD_OPTS="--build-arg BUILD_DATE=$BUILD_DATE --build-arg VCS_REF=$VCS_REF --build-arg VERSION=$VERSION"
if [ ! -z "$DOCKERFILE_PATH" ]; then
    export DOCKER_BUILD_OPTS="--file $DOCKERFILE_PATH $DOCKER_BUILD_OPTS"
fi

echo "* Now building frpc:v$VERSION..."
cp Dockerfile Dockerfile.original

build_docker_image() {
    PREFIX=$1
    ARCH=$2
    sed "s#frp-builds#$BUILD_DIR#" Dockerfile.original > Dockerfile
    sed -i "s/amd64/$ARCH/" Dockerfile
    docker build -t $DOCKER_REPO:$PREFIX-v$VERSION $DOCKER_BUILD_OPTS .
}

echo
echo "* Building docker image for amd64..."
docker build -t $DOCKER_REPO:v$VERSION $DOCKER_BUILD_OPTS .

echo
echo "* Building docker image for i386..."
build_docker_image i386 386

arch_all='arm arm64 mips64 mips64le mips mipsle'
for arch in $arch_all; do
    echo
    echo "* Building docker image for $arch..."
    build_docker_image $arch $arch
done

mv -f Dockerfile.original Dockerfile
