#!/bin/sh

export FRP_DOCKER_IMAGE_BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`

echo '* Downloading frp source code...'
git clone https://github.com/fatedier/frp.git
cd frp
export FRP_LATEST_VERSION=`git tag --sort=v:refname | grep '^v' | tail -n1 | tr -d v`
export FRP_VCS_REF=`git rev-list --abbrev-commit -1 v$FRP_LATEST_VERSION`
echo "* Latest frp version is v$FRP_LATEST_VERSION, git commit is $FRP_VCS_REF"
cd ..

echo "* Downloading prebuilt frp (v$FRP_LATEST_VERSION) binaries..."
curl -LO https://github.com/fatedier/frp/releases/download/v${FRP_LATEST_VERSION}/frp_${FRP_LATEST_VERSION}_linux_amd64.tar.gz
tar zxf frp_${FRP_LATEST_VERSION}_linux_amd64.tar.gz
rm -f frp_${FRP_LATEST_VERSION}_linux_amd64/frps*

echo "* Now building frpc:v$FRP_LATEST_VERSION..."
docker build --pull \
             --tag $DOCKER_REPO:v$FRP_LATEST_VERSION \
             --build-arg BUILD_DATE=$FRP_DOCKER_IMAGE_BUILD_DATE \
             --build-arg VCS_REF=$FRP_VCS_REF \
             --build-arg VERSION=$FRP_LATEST_VERSION \
             .
