#!/bin/sh

set -e

echo '* Downloading frp source code...'
git clone https://github.com/fatedier/frp.git

. ../scripts/_env.sh

echo "* Latest stable frp version is v$FRP_LATEST_VERSION"
echo "* Currently frp version is v$FRP_VERSION, git commit is $FRP_VCS_REF"

sed -i "s/\${VERSION}/v$FRP_VERSION/g" README.md
sed -i "s#leonismoe/frpc\.svg#leonismoe/frpc:v$FRP_VERSION.svg#g" README.md
