#!/bin/sh

set -e
. ../scripts/_env.sh

docker push $DOCKER_REPO:v$FRP_VERSION

if [ "$FRP_VERSION" = "$FRP_LATEST_VERSION" ]; then
    docker tag $DOCKER_REPO:v$FRP_VERSION $DOCKER_REPO:latest
    docker push $DOCKER_REPO:latest
fi

push_docker_image_by_arch() {
    ARCH=$1
    docker push $DOCKER_REPO:$ARCH-v$FRP_VERSION
    if [ "$FRP_VERSION" = "$FRP_LATEST_VERSION" ]; then
        docker tag $DOCKER_REPO:$ARCH-v$FRP_VERSION $DOCKER_REPO:$ARCH-latest
        docker push $DOCKER_REPO:$ARCH-latest
    fi
}

push_docker_image_by_arch i386
push_docker_image_by_arch arm32v6
push_docker_image_by_arch arm64v8
