#!/bin/sh

set -e

FRP_DOCKER_IMAGE_BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
. ../scripts/_env.sh


echo "* Now building frps:v$FRP_VERSION..."
sed 's#^RUN ln -s /usr/local/frp/#COPY --chown=root:root frp_linux/#' Dockerfile > Dockerfile.build

build_frp_docker_image() {
    PREFIX=$1
    ARCH=$2
    sed "s#^FROM alpine#FROM $PREFIX/alpine#" Dockerfile.build > Dockerfile
    sed -i "s#frp_linux#frp_${FRP_VERSION}_linux_${ARCH}#g" Dockerfile
    docker build --pull -t $DOCKER_REPO:$PREFIX-v$FRP_VERSION $DOCKER_BUILD_OPTS .
    docker tag $DOCKER_REPO:$PREFIX-v$FRP_VERSION $DOCKER_REPO:$PREFIX-latest
    rm -rf frp_${FRP_VERSION}_linux_${ARCH}
}

echo "* Building for x86_64 and amd64..."
mv frp_${FRP_VERSION}_linux_amd64 frp_linux
docker build --pull -t $DOCKER_REPO:v$FRP_VERSION $DOCKER_BUILD_OPTS .
rm -rf frp_linux

echo "* Building for x86..."
build_frp_docker_image i386 386

echo "* Building for arm..."
build_frp_docker_image arm32v6 arm

echo "* Building for arm64..."
build_frp_docker_image arm64v8 arm64

rm -f Dockerfile.build
git checkout -- Dockerfile
