#!/bin/sh

set -e

. ../scripts/_env.sh

echo "* Downloading prebuilt frp (v$FRP_VERSION)..."
download_frp() {
    ARCH=$1
    echo "  * Downloading $ARCH..."
    curl -LO https://github.com/fatedier/frp/releases/download/v${FRP_VERSION}/frp_${FRP_VERSION}_linux_${ARCH}.tar.gz
    tar zxf frp_${FRP_VERSION}_linux_${ARCH}.tar.gz
    rm -f frp_${FRP_VERSION}_linux_${ARCH}/frpc*
}

download_frp 386
download_frp amd64
download_frp arm
download_frp arm64
