#!/bin/bash

set -e

export DOCKER_CLI_EXPERIMENTAL=enabled

DOCKER_BUILD_OPTS="--build-arg CHECKOUT_VERSION=$VERSION"
if [ `docker version -f '{{.Server.Experimental}}'` = 'true' ]; then
  DOCKER_BUILD_OPTS="$DOCKER_BUILD_OPTS --squash"
fi

if [ ! -z "$DOCKERFILE_PATH" ]; then
  DOCKER_BUILD_OPTS="$DOCKER_BUILD_OPTS --file $DOCKERFILE_PATH"
fi

echo '==> preparing for build'
docker build -t $DOCKER_REPO:build-temp --target=build $DOCKER_BUILD_OPTS .

# copy `.env` out and apply it
ctid=$(docker create $DOCKER_REPO:build-temp)
docker cp $ctid:/build/.env $PWD/.env.local
docker rm -fv $ctid

ORIGINAL_VERSION=$VERSION
. $PWD/.env.local

DOCKER_BUILD_OPTS="$DOCKER_BUILD_OPTS --build-arg VERSION=${ORIGINAL_VERSION:+$VERSION}"

echo
echo '==> building'
docker build -t $DOCKER_REPO:$VERSION $DOCKER_BUILD_OPTS .

# cleanup
docker rmi $DOCKER_REPO:build-temp > /dev/null
