name: Build frp

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'target frp version'
        required: false
        default: ''

env:
  VERSION: ${{ github.event.inputs.version }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into DockerHub
        if: ${{ github.event_name != 'pull_request' && github.actor == env.DOCKERHUB_USERNAME }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log into GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frpc
        env:
          DOCKER_REPO: "${{ github.actor }}/frpc"
        working-directory: frp/frpc
        run: |
          ../hooks/build
          echo "::set-env name=VERSION::$VERSION"
          echo "::set-env name=LATEST_VERSION::$LATEST_VERSION"

          export DOCKER_REPO="ghcr.io/$DOCKER_REPO"
          ../hooks/build

      - name: Build frps
        env:
          DOCKER_REPO: "${{ github.actor }}/frps"
        working-directory: frp/frps
        run: |
          ../hooks/build

          export DOCKER_REPO="ghcr.io/$DOCKER_REPO"
          ../hooks/build

      - name: Push to DockerHub
        if: ${{ github.event_name != 'pull_request' && github.actor == env.DOCKERHUB_USERNAME }}
        working-directory: frp
        run: |
          (cd frpc && export DOCKER_REPO="${{ github.actor }}/frpc" && ../hooks/push)
          (cd frps && export DOCKER_REPO="${{ github.actor }}/frps" && ../hooks/push)

      - name: Push to GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        working-directory: frp
        run: |
          (cd frpc && export DOCKER_REPO="ghcr.io/${{ github.actor }}/frpc" && ../hooks/push)
          (cd frps && export DOCKER_REPO="ghcr.io/${{ github.actor }}/frps" && ../hooks/push)

      - name: Cleanup
        run: |
          if [ ! -z "$(docker images -q -f 'reference=${{ github.actor }}/frp*')" ]; then
            docker rmi $(docker images -q -f 'reference=${{ github.actor }}/frp*')
          fi
          docker image prune -f
