name: Build frp

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'target frp version'
        required: false
        default: ''

env:
  VERSION: ${{ github.event.inputs.version }}
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        program: [frpc, frps]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into DockerHub
        if: ${{ github.event_name != 'pull_request' && github.actor == env.DOCKERHUB_USERNAME }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log into GitHub Packages
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        env:
          DOCKER_REPO: "${{ github.actor }}/${{ matrix.program }}"
          GHCR_REPO: "ghcr.io/${{ github.actor }}/${{ matrix.program }}"
          PROGRAM: ${{ matrix.program }}
        working-directory: frp
        run: |
          ./build.sh $PROGRAM
