name: Trigger Docker Build When Package Releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  check-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          key: rss-cache-releases
          path: ./.cache/rss-cache-releases
      - run: ./_scripts/check-update-and-trigger-docker-build
        env:
          PKG_ARIANG_WEBHOOK: ${{ secrets.PKG_ARIANG_WEBHOOK }}
          PKG_FRPC_WEBHOOK: ${{ secrets.PKG_FRPC_WEBHOOK }}
          PKG_FRPS_WEBHOOK: ${{ secrets.PKG_FRPS_WEBHOOK }}
